export { default as logo } from "./logo.png";
export { default as comingSoon } from "./coming-soon.jpg";
export { default as comingSoonTiny } from "./coming-soon-tiny.jpg";
export { default as github } from "./github.png";
// export { default as telegram } from "./telegram.png";
export { default as google } from "./google.png";
export { default as linkedin } from "./linkedin.png";
export { default as hi } from "./hi.gif";
export { default as me } from "./me.jpg";
export { default as meTiny } from "./me-tiny.jpg";
